### PR TITLE
Polishing the window glass effect

### LINKED ISSUE #30: properly style the aero stripes/glass reflection effect
image

### PR DESCRIPTION
**Pull request by hohaicongthuan**
Add the glass stripes/reflection effect.

It's not an exact replica but I think it's close enough.

I've also put together a small [demo here](https://codepen.io/hohaicongthuan/pen/MWZBGqj) with draggable windows.

### CODE REVIEW

**Comment by hohaicongthuan** [comment]
Also, should I make those glass stripe effects optional? Because, on second thought, that's a lot of gradients, some low-end and mobile devices might have difficulty rendering those.

**Review by khang-nd — CHANGES_REQUESTED** [review]
This is solid work @hohaicongthuan, super impressed 🤯 But as we can notice some performance drawbacks, let's keep these gradients in a utility class (maybe chuck them in the same `.glass` class) so users can opt-in if they want to experience the glass reflection effect.

**Comment by hohaicongthuan** [comment]
Okay, I've moved it to the `.glass` class. I've also made these windows wider to make the glass effects more noticeable.

Screenshot_20231026_133538

**Review by khang-nd — APPROVED** [review]
Looks good to me, thanks mate 👍

**Pull request merged**
